name: deploy-book

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BASE_URL: /${{ github.event.repository.name }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-book:
    if: contains(github.event.head_commit.message, '#build')
    runs-on: self-hosted
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      # Step 2: Get the GitHub username from the commit metadata
      - name: Get GitHub username
        id: commit_user
        run: |
          AUTHOR_USERNAME=$(jq -r '.head_commit.author.username' < "$GITHUB_EVENT_PATH")
          echo "GitHub Username: $AUTHOR_USERNAME"
          echo "author_username=$AUTHOR_USERNAME" >> $GITHUB_ENV

      # Step 3: Check if the username matches the target user
      - name: Check commit author
        run: |
          if [[ "$author_username" != "jagar2" ]]; then
            echo "This commit was not made by jagar2. Exiting. $author_username"
            exit 1
          fi

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r jupyterbook/requirements.txt

      - name: Build the book
        run: |
          rm -rf ./jupyterbook/_build
          rm -rf ./jupyterbook/_config.yml
          cp -rf ./_config.yml ./jupyterbook
          jupyter-book build ./jupyterbook

      - name: Check if SMB share is available
        run: |
          if [ ! -d "/mnt/drexel_web/josh-dev" ]; then
            echo "SMB share not available, exiting."
            exit 1
          fi

      - name: Upload and Deploy
        if: contains(github.event.head_commit.message, '#dev')
        run: |
          SMBSHARE="/mnt/drexel_web/josh-dev"
          JBPATH="./jupyterbook"
          echo "Deploying to $SMBSHARE"
          rm -rf $SMBSHARE/*
          cp -rf --remove-destination $JBPATH/_build/html/* $SMBSHARE
          cp -rf ./assets/web.config $SMBSHARE
